# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  pmp_hosts:
    sandbox:
      host:          "https://api-sandbox.pmp.io"
      client_id:     "<%= ENV['SANDBOX_CLIENT_ID'] %>"
      client_secret: "<%= ENV['SANDBOX_CLIENT_SECRET'] %>"
    production:
      host:          "https://api.pmp.io"
      client_id:     "<%= ENV['PRODUCTION_CLIENT_ID'] %>"
      client_secret: "<%= ENV['PRODUCTION_CLIENT_SECRET'] %>"
  gmail_username:  "<%= ENV['GMAIL_USERNAME'] %>"
  gmail_password:  "<%= ENV['GMAIL_PASSWORD'] %>"

development:
  <<: *defaults
  secret_key_base: "6425f432147835cfd64f020e63a2e13eab00fafd6516f37e3cbec97753b48407cd63d134a23ca45aaaaf7146f11a289c76861bb5c4aa28529f4f78f0a38c53d1"

test:
  <<: *defaults
  secret_key_base: "b01ccfb63ec645734ad39990aaf13b30dd1c2fe39e9b23314bcbdf3ee97c2815d2a55a7dd715351bd5e8735b6364209266f2fcde8635bc080a594f9e2bcd253d"

# hide production secrets
production:
  <<: *defaults
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"
